# Default values for getmesh.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: gentics/mesh
  tag: 0.31.5
  pullPolicy: IfNotPresent

global: {}
  #uncomment with the right domain
  #domain: mydomain.com


ingress:
  enabled: true
  tls: true
  acme: false #if true will generate https certificate via letsencrypt
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8m

monitoring: false

resources:
   limits:
    cpu: 1000m
    memory: 2048Mi
   requests:
    cpu: 500m
    memory: 1024Mi

persistence:
  backup:
    enabled: true # if true will create a backup cronjob (only active if nfs is available)
    schedule: "0 3 * * *"
    keepDays: 60 # purge will remove backup older than this value in days
  enabled: true

  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined,  PVC must be created manually before volume will be bound
  # existingClaim:
  storageClass: "ssd"
  accessModes:
  - ReadWriteOnce
  size: 10Gi

  # nfs informations can be retreive with cmd
  # gcloud beta filestore instances list --project=project-id
  # nfs is used only is persistence is enabled
  # nfs is used to mount uploads volume (shared between master and replicas)
  # nfs is MANDATORY when using mesh.cluster with replicas
  nfs:
    enabled: true # if false same regular data volume will be used (NB: so binaries uploads will not be shared among getmesh instances)
    storage: 20Gi
    path: /default #NFS SERVER PATH
    server: X.X.X.X #NFS SERVER IP

readinessProbe:
  httpGet: {}

livenessProbe:
  httpGet: {}

prometheusName: prometheus-operator

getmesh:
  ui:
    image: registry.auchanlab.com/getmesh/mesh-ui:0.9.4
  master:
    tolerations:
  additionalEnvironmentVariables:
    # https://getmesh.io/docs/administration-guide/
    JAVA_TOOL_OPTIONS: "-Xms512m -Xmx786m -XX:MaxDirectMemorySize=384m -Dstorage.diskCache.bufferSize=384 -Dhazelcast.diagnostics.enabled=true"
  cluster:
    enabled: true #NB: if cluster enabled nfs persistence SHOULD be enabled too
    replicas: 2 #if cluster enabled is false set replicas count to 0

elasticsearch:
  enabled: true #if not enabled, es will be started in getmesh container, else es will be started outside using official elasticsearch chart
  # getmesh use elasticsearch-oss 6.1.4
  image:
    tag: 6.1.4
  url: http://{{ .Release.Name }}-elasticsearch-client:9200
  data:
    antiAffinity: "hard"
    persistence:
      size: "10Gi"
      storageClass: ssd
  client:
    antiAffinity: "hard"
  master:
    antiAffinity: "hard"
    persistence:
      size: "4Gi"
      storageClass: ssd
  cluster: #quick and dirty fix to get cluster name relative to discovery service fullname (differents clusters cant join each others)
    name: c-${DISCOVERY_SERVICE}

autoscaling:
  enabled: false
  maxReplicas: 5
  minReplicas: 2
  targetCPUUtilizationPercentage: 80 # percent against request cpu
