apiVersion: v1
kind: Service
metadata:
  name: {{ template "getmesh.fullname" . }}-anygetmesh
  labels:
    app: {{ template "getmesh.name" . }}
    chart: {{ template "getmesh.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ template "getmesh.name" . }}
    release: {{ .Release.Name }}
