#see https://github.com/hazelcast/hazelcast-kubernetes
apiVersion: v1
kind: Service
metadata:
  name: {{ template "getmesh.fullname" . }}-hazelcast
  labels:
    app.kubernetes.io/name: {{ include "getmesh.name" . }}
    helm.sh/chart: {{ include "getmesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5701
    name: hazelcast
    targetPort: hazelcast
  selector:
    app.kubernetes.io/name: {{ include "getmesh.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: getmesh-api
{{/*    release: {{ .Release.Name }}*/}}
{{/*    #role: master*/}}
{{/*    app: {{ template "getmesh.name" . }}*/}}
{{/*    #statefulset.kubernetes.io/pod-name*/}}
