apiVersion: v1
kind: Service
metadata:
  name: {{ template "getmesh.fullname" . }}-master
  labels:
    app.kubernetes.io/name: {{ include "getmesh.name" . }}
    helm.sh/chart: {{ include "getmesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    role: master
    release: {{ .Release.Name }}
    app.kubernetes.io/monitoring: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: legacy-http
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: monitoring
  selector:
    app.kubernetes.io/name: {{ include "getmesh.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: getmesh-master
