apiVersion: v1
kind: Service
metadata:
  name: {{ template "getmesh.fullname" . }}-ui
  labels:
    app: {{ template "getmesh.name" . }}
    chart: {{ template "getmesh.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "getmesh.name" . }}-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
