{{- if .Values.monitoring }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "getmesh.fullname" . }}-elasticsearch-exporter
  labels:
    app.kubernetes.io/name: {{ include "getmesh.name" . }}
    helm.sh/chart: {{ include "getmesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    role: elasticsearch-exporter
    app.kubernetes.io/monitoring: "true"
spec:
  type: ClusterIP
  ports:
    - name: monitoring
      port: 9108
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "getmesh.name" . }}-elasticsearch-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end}}
