{
 "title": "Getmesh",
 "description": "Getmesh dashboard 0.31.5 v1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "release", "query": "label_values(release)" }
  ]
 },
 "panels": [
  {
   "title": "Mesh master UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{release=~\"$release\", role=\"master\"})"
    }
   ]
  },
  {
   "title": "Mesh replicas UP",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{release=~\"$release\", role=\"replicas\"})"
    }
   ]
  },
  {
   "title": "Request count rate by code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_servers_0_0_0_0:8080_responses_2xx_total{release=\"$release\"}[1m])) by (service)",
     "legendFormat": "2xx {{service}}"
    },
    {
     "expr": "sum(irate(vertx_http_servers_0_0_0_0:8080_responses_3xx_total{release=\"$release\"}[1m])) by (service)",
     "legendFormat": "3xx {{service}}"
    },
    {
     "expr": "sum(irate(vertx_http_servers_0_0_0_0:8080_responses_1xx_total{release=\"$release\"}[1m])) by (service)",
     "legendFormat": "1xx {{service}}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vertx_http_servers_0_0_0_0:8080_open_netsockets{release=\"$release\"}) by (pod)"
    },
    {}
   ]
  },
  {
   "title": "Request count rate by error code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_servers_0_0_0_0:8080_responses_5xx_total{release=\"$release\"}[1m])) by (pod)",
     "legendFormat": "5xx {{pod}}"
    },
    {
     "expr": "sum(irate(vertx_http_servers_0_0_0_0:8080_responses_4xx_total{release=\"$release\"}[1m])) by (pod)",
     "legendFormat": "4xx {{pod}}"
    }
   ]
  },
  {
   "title": "Avg per percentiles mesh master responses times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vertx_http_servers_0_0_0_0:8080_requests{release=\"$release\", role=\"master\"}) by (service,quantile)"
    }
   ]
  },
  {
   "title": "Average percentiles replicas responses times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(vertx_http_servers_0_0_0_0:8080_requests{release=\"$release\", role=\"replicas\"}) by (service,quantile)"
    }
   ]
  },
  {
   "title": "HTTP Server bytes sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(vertx_http_servers_0_0_0_0:8080_bytes_written{release=\"$release\",quantile=\"0.999\"}[1m])) by (service)"
    }
   ]
  },
  {
   "title": "HTTP Server bytes received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(vertx_http_servers_0_0_0_0:8080_bytes_read{release=\"$release\",quantile=\"0.999\"}[1m])) by (service)"
    }
   ]
  },
  {
   "title": "Getmesh tx rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mesh_tx_created_total{release=~\"$release\"}[1m])) by (service)"
    }
   ]
  },
  {
   "title": "Getmesh no tx rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mesh_notx_created_total{release=~\"$release\"}[1m])) by (service)"
    }
   ]
  },
  {
   "title": "Eventbus: handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_eventbus_handlers{release=\"$release\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Eventbus: pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_eventbus_messages_pending{release=\"$release\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Eventbus: sent rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_messages_bytes_written_total{release=\"$release\"}[1m])) by (service)",
     "legendFormat": "1 minute instant rate {{service}}"
    }
   ]
  },
  {
   "title": "Eventbus: received rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_messages_bytes_written_total{release=\"$release\"}[1m])) by (service)",
     "legendFormat": "1 minute instant rate {{service}}"
    }
   ]
  },
  {
   "title": "Vertx blocking usage ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_pools_worker_vert_x_internal_blocking_pool_ratio{release=\"$release\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "mesh_tx_time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mesh_tx_time{release=\"$release\"}[1m])) by (service, quantile)"
    }
   ]
  },
  {
   "title": "mesh_tx_retry",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mesh_tx_retry{release=\"$release\"}[1m])) by (service, quantile)"
    }
   ]
  }
 ]
}