{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "getmesh.fullname" . }}
  labels:
    app: {{ template "getmesh.name" . }}
    chart: {{ template "getmesh.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingressClass | default "nginx" }}
    kubernetes.io/tls-acme: "false"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~ ^/$ {
          return 301 $pass_access_scheme://{{ printf "%s-ui.%s.%s" .Chart.Name .Release.Name .Values.global.domain | trimSuffix "-" }};
      }

{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
      - hosts:
        - {{ template "getmesh.host" . }}
        - {{ template "getmesh.host-replicas" . }}
        - {{ template "getmesh.host-backup-explorer" . }}
        secretName: {{ template "certificate.fullname" . }}
  {{- end }}
  rules:
    - host: {{ template "getmesh.host" . }}
      http:
        paths:
          #redirect to new ui
          - path: /
            backend:
              serviceName: {{ template "getmesh.fullname" . }}-ui
              servicePort: http
          - path: /api
            backend:
              serviceName: {{ template "getmesh.fullname" . }}-master
              servicePort: http
{{- end }}
