### THIS FILE IS DEFAULT UNCHANGED ONE : all overrides are made by environment variables
---
defaultMaxDepth: 10
defaultLanguage: "en"
updateCheck: true # override to false MESH_UPDATECHECK
vertxOptions:
  workerPoolSize: 20 # 40 #double value to prevent a stuck under heavy load /children (bug needs to be fixed)
  eventPoolSize: 8 # 16 #com.gentics.mesh.core.endpoint.node.NodeCrudHandler.lambda$handleReadChildren$11(NodeCrudHandler.java:214)
tempDirectory: "data/tmp"
pluginDirectory: "plugins"
pluginTimeout: 15
nodeName: "Undulating Luvdisc" #MESH_NODE_NAME
httpServer:
  port: 8080
  host: "0.0.0.0"
  corsAllowedOriginPattern: ""
  corsAllowCredentials: false
  enableCors: false
  ssl: false
  certPath: "config/cert.pem"
  keyPath: "config/key.pem"
monitoring:
  enabled: true
  port: 8081
  host: "127.0.0.1" # override to 0.0.0.0
cluster: #MESH_CLUSTER_NAME #MESH_CLUSTER_NETWORK_HOST
  enabled: false #MESH_CLUSTER_ENABLED
  vertxPort: 0 #MESH_CLUSTER_VERTX_PORT=4848 https://github.com/gentics/mesh/issues/519
  #networkHost: "0.0.0.0" # MESH_CLUSTER_NETWORK_HOST
storage:
  directory: "data/graphdb" # override to /graphdb
  backupDirectory: "data/backup" # /backups-nfs/orientdb #MESH_GRAPH_BACKUP_DIRECTORY
  exportDirectory: "data/export"
  startServer: false
  synchronizeWrites: true
  txRetryDelay: 10
  txRetryLimit: 10
  parameters: {}
search:
  url: "http://localhost:9200" #MESH_ELASTICSEARCH_URL
  hostnameVerification: true
  timeout: 60000
  startupTimeout: 45
  startEmbedded: true #MESH_ELASTICSEARCH_START_EMBEDDED
  embeddedArguments: "-Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75\
    \ -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -client -Xss1m -Djava.awt.headless=true\
    \ -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true\
    \ -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0\
    \ -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -XX:+HeapDumpOnOutOfMemoryError"
  prefix: "mesh-"
  bulkLimit: 100
  bulkLengthLimit: 5000000
  eventBufferSize: 1000
  bulkDebounceTime: 2000
  idleDebounceTime: 100
  retryInterval: 5000
  retryLimit: 3
  waitForIdle: true
  includeBinaryFields: true
  mappingMode: "DYNAMIC"
upload:
  byteLimit: 262144000
  directory: "data/binaryFiles" # override to /uploads #MESH_BINARY_DIR
  tempDirectory: "data/tmp/file-uploads"
  parserLimit: 40000
  parser: true
security:
  tokenExpirationTime: 3600
  keystorePassword: "MESH_AUTH_KEYSTORE_PASS" #MESH_AUTH_KEYSTORE_PASS
  keystorePath: "config/keystore.jceks" #MESH_AUTH_KEYSTORE_PATH
  algorithm: "HS256"
  enableAnonymousAccess: true
  oauth2:
    enabled: false
    mapperScriptPath: "config/mymapper.js"
    mapperScriptDevMode: true
    config:
      realm: "internal"
      authServerUrl: "https://oidc-itg.gcp.dvl.auchan.net:443/auth" #MESH_AUTH_OAUTH2_SERVER_CONF_AUTH_SERVER_URL
      sslRequired: "external"
      resource: "getmesh"
      credentials:
        secret: "9b65c378-5b4c-4e25-b5a1-a53a381b5fb4"
      confidentialPort: 0
image:
  imageCacheDirectory: "data/binaryImageCache"
  maxWidth: 2048
  maxHeight: 2048
  jpegQuality: 0.95
  resampleFilter: "LANCZOS"
content:
  autoPurge: true
cache:
  pathCacheSize: 20000
