---
defaultMaxDepth: 10
defaultLanguage: "en"
languagesFilePath: null
updateCheck: true
vertxOptions:
  workerPoolSize: 20
  eventPoolSize: 8
tempDirectory: "data/tmp"
pluginDirectory: "plugins"
pluginTimeout: 15
nodeName: "Scampering Hydreigon"
httpServer:
  port: 8080
  host: "0.0.0.0"
  corsAllowedOriginPattern: ""
  corsAllowCredentials: false
  enableCors: false
  ssl: false
  certPath: "config/cert.pem"
  keyPath: "config/key.pem"
monitoring:
  enabled: true
  port: 8081
  host: "127.0.0.1"
cluster:
  networkHost: null
  enabled: false
  clusterName: null
  vertxPort: 0
storage:
  directory: "data/graphdb"
  backupDirectory: "data/backup"
  exportDirectory: "data/export"
  startServer: false
  synchronizeWrites: true
  txRetryDelay: 10
  txRetryLimit: 10
  parameters: {}
search:
  url: null
  username: null
  password: null
  certPath: null
  caPath: null
  hostnameVerification: true
  timeout: 60000
  startupTimeout: 45
  startEmbedded: false
  embeddedArguments: "-Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75\
    \ -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -client -Xss1m -Djava.awt.headless=true\
    \ -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true\
    \ -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0\
    \ -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -XX:+HeapDumpOnOutOfMemoryError"
  prefix: "mesh-"
  bulkLimit: 100
  bulkLengthLimit: 5000000
  eventBufferSize: 1000
  bulkDebounceTime: 2000
  idleDebounceTime: 100
  retryInterval: 5000
  retryLimit: 3
  waitForIdle: true
  includeBinaryFields: true
  mappingMode: "DYNAMIC"
upload:
  byteLimit: 262144000
  directory: "data/binaryFiles"
  tempDirectory: "data/tmp/file-uploads"
  parserLimit: 40000
  parser: true
security:
  tokenExpirationTime: 3600
  keystorePassword: "4c65bebaf4204cb2a5bebaf420ecb2cf"
  keystorePath: "config/keystore.jceks"
  algorithm: "HS256"
  enableAnonymousAccess: true
  publicKeysPath: "config/public-keys.json"
image:
  imageCacheDirectory: "data/binaryImageCache"
  maxWidth: 2048
  maxHeight: 2048
  jpegQuality: 0.95
  resampleFilter: "LANCZOS"
content:
  autoPurge: true
cache:
  pathCacheSize: 20000
