apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "getmesh.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: {{ include "getmesh.name" . }}
    helm.sh/chart: {{ include "getmesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "getmesh.name" . }}-ui
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "getmesh.name" . }}-ui
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: ui
          image: "cschockaert/mesh-ui:0.9.3"
          imagePullPolicy: Always
          env:
            - name: "GETMESH_API_HOST"
              value: {{ template "getmesh.fullname" . }}-master.{{ .Release.Namespace }}.svc.cluster.local:8080
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 25m
              memory: 32Mi

