apiVersion: v1
kind: Secret
metadata:
  name: {{ template "getmesh.fullname" . }}
  labels:
    app: {{ template "getmesh.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  mesh-initial-admin-password: {{ .Values.getmesh.adminPassword | b64enc | quote }}
